-- BANCO DA TABELA PRODUTO(inserção)
-- CREATE TABLE produto(codigoProduto int(11), descicao varchar(45), preco decimal(4,2), 
-- 			statusProduto bit(1), tipoProduto varchar(30), primary key(codigoProduto));

INSERT INTO produto VALUES (1, 'Acai 150ml', 5.00, 1, 'Copo');
INSERT INTO produto VALUES (2, 'Acai 200ml', 6.50, 1, 'Copo');
INSERT INTO produto VALUES (3, 'Acai 300ml', 8.50, 1, 'Copo');
INSERT INTO produto VALUES (4, 'Acai 400ml', 10.50, 1, 'Copo'); 
INSERT INTO produto VALUES (5, 'Acai 500ml', 14.50, 1, 'Copo');
INSERT INTO produto VALUES (6, 'Acai 750ml', 18.50, 1, 'Copo');
INSERT INTO produto VALUES (7, 'Granola Tradicional', 0.00, 1, 'Grao');
INSERT INTO produto VALUES (8, 'Granola com Banana', 0.00, 1, 'Grao');
INSERT INTO produto VALUES (9, 'Granola com Aveia',	0.00, 1, 'Grao');
INSERT INTO produto VALUES (10, 'Granola de Castanha', 0.00, 1, 'Grao');
INSERT INTO produto VALUES (11, 'Granola de Chocolate', 0.00, 1, 'Grao');
INSERT INTO produto VALUES (12, 'Granola Light',	0.00, 1, 'Grao');
INSERT INTO produto VALUES (13, 'Flocos de Tapioca',	0.00, 1, 'Grao');
INSERT INTO produto VALUES (14, 'Flocos de Arroz', 0.00, 1, 'Grao');
INSERT INTO produto VALUES (15, 'Cereal Ball Chocolate', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (16, 'Coco Ralado', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (17, 'Coco Ralado Queimado', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (18, 'Doce de Leite', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (19, 'Granulado de Chocolate', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (20, 'Jujuba', 0.00, 1, 'Codimento');
INSERT INTO produto VALUES (21, 'Chocolate', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (22, 'Caramelo', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (23, 'Morango', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (24, 'Leite Condensado', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (25, 'Mel de Abelha', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (26, 'Mel de Engenho', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (27, 'Kiwi', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (28, 'Limao', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (29, 'Menta', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (30, 'Doce de Leite Calda', 0.00, 1, 'Calda');
INSERT INTO produto VALUES (31, 'Amora', 1.00, 1, 'Calda Premium');
INSERT INTO produto VALUES (32, 'Maracuja', 1.00, 1, 'Calda Premium');
INSERT INTO produto VALUES (33, 'Xarope de Guarana', 1.00, 1, 'Calda Premium');
INSERT INTO produto VALUES (34, 'Aveia', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (35, 'Aveia em flocos', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (36, 'Neston', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (37, 'Ovomaltine', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (38, 'Farinha Lactea', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (39, 'Leite em Po', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (40, 'Amendoim', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (41, 'Amendoim Granulado', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (42, 'Farinha de Amendoim', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (43, 'Pacoca', 0.00, 1, 'Cereais');
INSERT INTO produto VALUES (44, 'Abacaxi', 0.00, 1, 'Frutas');
INSERT INTO produto VALUES (45, 'Banana', 0.00, 1, 'Frutas');
INSERT INTO produto VALUES (46, 'Morango', 1.50, 1, 'Frutas');
INSERT INTO produto VALUES (47, 'Manga', 0.00, 1, 'Frutas');
INSERT INTO produto VALUES (48, 'Kiwi', 1.50, 1, 'Frutas');
INSERT INTO produto VALUES (49, 'Uvas Passas', 0.00, 1, 'Frutas');
INSERT INTO produto VALUES (50, 'Castanha', 3.00, 1, 'Extra');
INSERT INTO produto VALUES (51, 'Whey Protein', 3.00, 1, 'Extra');
INSERT INTO produto VALUES (52, 'Leite Condensado sem Lactose', 0.00, 1, 'Doce');
INSERT INTO produto VALUES (53, 'Creme de Ovomaltine com Avela', 3.00, 1, 'Extra');
INSERT INTO produto VALUES (54, 'Nutella', 3.00, 1, 'Extra');
INSERT INTO produto VALUES (55, 'Pasta de Amedoim Integral', 3.00, 1, 'Extra');
INSERT INTO produto VALUES (56, 'Bis', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (57, 'MMs', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (58, 'Gotas de Chocolate', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (59, 'Oreo', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (60, 'Preparo de Morango', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (61, 'Preparo de Ameixa', 2.00, 1, 'Extra');
INSERT INTO produto VALUES (62, 'Pitaya', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (63, 'Cupuacu Trufado', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (64, 'Tapioca com Leite Condensado e Coco', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (65, 'Creme de Ninho', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (66, 'Morango e Leite Condensado', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (67, 'Detox', 1.50, 1, 'Extra');
INSERT INTO produto VALUES (68, 'Antiox', 1.50, 1, 'Extra');
